[package]
name = "pact-protobuf-plugin"
version = "0.3.1"
edition = "2021"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
description = "Pact plugin for Protobufs and gRPC"
homepage = "http://www.pactflow.io"
repository = "https://github.com/pactflow/pact-protobuf-plugin"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
tonic = "0.9.2"
prost = "0.11.9"
prost-types = "0.11.9"
tokio = { version = "1.28.2", features = ["full"] }
uuid = { version = "1.3.3", features = ["v4"] }
maplit = "1.0.2"
pact_matching = "~1.1.0"
pact_models = "~1.1.4"
pact_verifier = "~1.0.0"
pact-plugin-driver = "~0.4.4"
anyhow = "1.0.71"
futures = "0.3.28"
async-trait = "0.1.68"
os_info = "3.7.0"
zip = "0.6.6"
serde_json = "1.0.96"
serde_yaml = "0.9.21"
tempfile = "3.5.0"
itertools = "0.10.5"
md5 = "0.7.0"
base64 = "0.21.2"
bytes = "1.4.0"
clap = { version = "4.3.0", features = ["cargo", "env"] }
hyper = { version = "0.14.26", features = [ "full" ] }
http = "0.2.9"
tower = { version = "0.4.13", features = [ "full" ] }
tower-service = { version = "0.3.2" }
tower-http = { version = "0.4.0", features = [ "full" ] }
http-body = "0.4.5"
tracing = "0.1.37"
tracing-core = "0.1.31"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "local-time", "tracing-log"] }
tracing-appender = "0.2.2"
tracing-log = "0.1.3"
lazy_static = "1.4.0"
ansi_term = "0.12.1"
tracing-bunyan-formatter = "0.3.7"
chrono = { version = "0.4.26", features = ["std", "clock"], default_features = false }
rand = "0.8.5"
regex-syntax = "0.6.29"
regex = "1.8.3"
rand_regex = "0.15.1"

[dependencies.reqwest]
version = "0.11.18"
default-features = false
features = ["rustls-tls", "rustls-tls-native-roots", "json", "gzip", "deflate"]

[dev-dependencies]
expectest = "0.12"
env_logger = "0.10.0"
serde = "1.0.163"
rocket = "0.5.0-rc.3"
test-log = "0.2.11"
trim-margin = "0.1.0"
pact_consumer = "1.0.0"
home = "0.5.5"
panic-message = "0.3.0"

[build-dependencies]
built = { version = "0.6.0", features = [ "git2" ] }
os_info = "3.7.0"
